import type { Config, Context } from "@netlify/functions";
import { getDatabase } from "@netlify/database";
import { searchKnowledge, synthesizeKnowledgeAnswer } from "../lib/knowledge-core.mts";
const MODEL="gpt-4.1-mini";
const env=(n:string)=>{try{return Netlify.env.get(n)}catch{return undefined}}, txt=(v:any)=>String(v??"").trim(), J=(d:any,i:ResponseInit={})=>Response.json(d,i);
async function ai(messages:any[],json=false){const key=env("OPENAI_API_KEY"),base=env("OPENAI_BASE_URL"),model=env("HLK_MODEL")||MODEL;if(!key||!base)throw Error("AI_GATEWAY_UNAVAILABLE");const b:any={model,messages};if(json)b.response_format={type:"json_object"};const r=await fetch(`${base}/v1/chat/completions`,{method:"POST",headers:{"Content-Type":"application/json","Authorization":`Bearer ${key}`},body:JSON.stringify(b)});if(!r.ok)throw Error(`AI_GATEWAY_${r.status}`);const d:any=await r.json();return{text:txt(d.choices?.[0]?.message?.content),model}}
const parse=(s:string)=>JSON.parse(String(s||"").replace(/^```(?:json)?\s*/i,"").replace(/\s*```$/i,"").trim()||"{}");
async function catalog(db:any){const r=await db.pool.query(`SELECT a.asset_id,a.title,a.asset_type,a.description,a.fields,a.record_count,a.version_label,COALESCE(c.name,a.proposed_category) category FROM data_assets a LEFT JOIN reference_categories c ON c.category_id=a.category_id WHERE a.status='published' AND COALESCE(a.is_current,true)=true ORDER BY a.updated_at DESC NULLS LAST LIMIT 120`);return r.rows.map((x:any)=>({asset_id:x.asset_id,title:x.title,type:x.asset_type,category:x.category,fields:Array.isArray(x.fields)?x.fields.slice(0,40):[],record_count:x.record_count,version:x.version_label}))}
async function plan(q:string,ref:any,cat:any[]){const cap='人口/家庭/家庭成员/养老账户与缴费/民政关爱/应急事件与转移/应急费用/政策，以及 people_governance 跨域人员筛选';const r=await ai([{role:"system",content:'你是黄林坑村治理AI的Agent Planner，不是意图分类器。只决定完成用户目标需要调用什么能力，不回答用户，不写SQL。能力：structured_query=精确筛选/统计/比较/名单/金额/日期；knowledge_search=主题、情况、产业、活动、背景、总结等可能散落多资料的问题；general_response=不依赖黄林坑具体事实的一般讨论；system_help=系统使用；clarify=确实缺必要信息。不要因为出现村里/蜂蜜/养老/台风就机械选structured_query。“蜂蜜生产情况”优先knowledge_search；“70岁以上多少人”优先structured_query；既要数字又要背景可同时用structured_query和knowledge_search；“蜂蜜和乡村治理有什么关系”且没要求黄林坑事实用general_response。输出JSON：{"goal":"","tools":[{"tool":"knowledge_search","reason":""}],"answer_scope":"village_facts|general_analysis|system_usage"}'},{role:"user",content:`问题：${q}\n锁定资料：${JSON.stringify(ref||null)}\n系统结构化能力：${cap}\n已发布资料：\n${cat.map(x=>`${x.asset_id}|${x.type}|${x.category||""}|${x.title}|字段:${x.fields.join("/")}`).join("\n")}`}],true),o=parse(r.text),allow=new Set(['structured_query','knowledge_search','general_response','system_help','clarify']),tools=(Array.isArray(o.tools)?o.tools:[]).map((x:any)=>({tool:txt(x.tool),reason:txt(x.reason)})).filter((x:any)=>allow.has(x.tool)).slice(0,3);return{goal:txt(o.goal)||q,tools:tools.length?tools:[{tool:'clarify',reason:'没有可靠动作'}],answer_scope:txt(o.answer_scope)||'village_facts',model:r.model}}
async function structured(req:Request,body:any){const u=new URL(req.url);u.pathname='/api/query-v052-exec';const h=new Headers(req.headers);h.delete('content-length');const r=await fetch(new Request(u.toString(),{method:'POST',headers:h,body:JSON.stringify(body)}));return await r.json().catch(()=>({ok:false}))}
const answered=(d:any)=>!!(d?.ok&&!d?.result?.no_database_query&&!['clarify','data_gap'].includes(d?.result?.kind));
async function general(q:string){return ai([{role:'system',content:'你是黄林坑村治理AI里的AI村长。当前做一般讨论，不查询村级数据库。可以分析、建议、创意，但不得把一般知识说成黄林坑村具体事实。自然简洁，不要官腔。'},{role:'user',content:q}])}
function help(q:string){if(/上传/.test(q))return'管理员可从右上角“演示管理员 → 数据治理”上传资料，确认发布后才进入AI可查询范围。';if(/删除/.test(q))return'进入“演示管理员 → 数据治理 → 最近上传”，管理员上传资料右侧可删除；系统内置台账不可删除。';if(/依据|执行过程/.test(q))return'工作回答底部可以查看依据和执行过程；执行过程会显示Agent选了什么能力、检索了哪些资料，以及结构化查询真正生效的条件。';return'我可以正常聊天，也可以查询已发布结构化治理数据、搜索多份参考资料并说明依据。'}
async function fuse(q:string,s:any,k:any){if(k&&!s){const a=await synthesizeKnowledgeAnswer(q,k);return{text:a.direct_answer,sections:a.sections||[],conflicts:a.conflicts||[],claims:a.claims||[],model:a.model||'none'}}if(s&&!k)return{text:s.narrative||s.result?.summary||'查询已完成。',sections:[],conflicts:[],claims:[],model:s.model?.name||'none'};if(s&&k){try{const r=await ai([{role:'system',content:'你是最终答案融合器，只根据已验证结构化结果和已发布资料回答。结构化数字优先作为确定性数值事实；文档补背景；冲突必须指出，不得平均或猜测。输出JSON：{"direct_answer":"","sections":[],"conflicts":[]}'},{role:'user',content:`问题：${q}\n结构化结果：${JSON.stringify({summary:s.result?.summary,facts:s.result?.facts,rows:(s.result?.recordRows||s.result?.rows||[]).slice(0,30),filters:s.result?.filters})}\n知识资料：${JSON.stringify(k.sources.map((x:any)=>({title:x.title,version:x.version_label,excerpts:x.chunks.map((c:any)=>txt(c.text).slice(0,1200))})))}`}],true),o=parse(r.text);return{text:txt(o.direct_answer)||s.result?.summary,sections:Array.isArray(o.sections)?o.sections.slice(0,6):[],conflicts:Array.isArray(o.conflicts)?o.conflicts.slice(0,8):[],claims:[],model:r.model}}catch{return{text:s.narrative||s.result?.summary,sections:[],conflicts:[],claims:[],model:'none'}}}return{text:'当前已发布资料中还没有找到足够依据回答这个问题。',sections:[],conflicts:[],claims:[],model:'none'}}
async function handler(req:Request){if(req.method!=='POST')return J({ok:false,error:'method_not_allowed'},{status:405});const b:any=await req.json().catch(()=>({})),q=txt(b.query),ref=b.reference_context&&typeof b.reference_context==='object'?b.reference_context:null;if(!q)return J({ok:false,error:'query_required',message:'请输入问题。'},{status:400});const db=getDatabase(),cat=await catalog(db).catch(()=>[]);let p:any;try{p=await plan(q,ref,cat)}catch{p={goal:q,tools:[{tool:'knowledge_search',reason:'规划模型不可用，先检索已发布资料'}],answer_scope:'village_facts',model:'none'}}
if(p.tools[0]?.tool==='system_help'){const a=help(q);return J({ok:true,model:{mode:'agent-v053',name:p.model},plan:{intent:'agent',goal:p.goal,steps:[{tool:'system_help'}],note:'系统使用说明 · 未查询数据库'},result:{kind:'system_help',domain:'使用帮助',title:'系统使用说明',summary:a,facts:[],rows:[],columns:[],recordRows:[],filters:[],evidence:[],tools:[],no_database_query:true},narrative:a,generated_at:new Date().toISOString()})}
if(p.tools[0]?.tool==='clarify'){const a='我还缺少一个能决定下一步动作的关键信息。你可以再具体一点说明想了解的对象、范围或时间。';return J({ok:true,model:{mode:'agent-v053',name:p.model},plan:{intent:'agent',goal:p.goal,steps:[],note:'Agent需要澄清'},result:{kind:'clarify',domain:'意图确认',title:'需要再确认一下',summary:a,facts:[],rows:[],columns:[],recordRows:[],filters:[],evidence:[],tools:[],no_database_query:true},narrative:a,generated_at:new Date().toISOString()})}
if(p.tools[0]?.tool==='general_response'&&p.tools.length===1){try{const a=await general(q);return J({ok:true,model:{mode:'agent-v053-general',name:a.model,gateway:true},plan:{intent:'agent',goal:p.goal,steps:[{tool:'general_response',params:{database:false}}],note:'一般讨论 · 未查询村级事实库'},result:{kind:'chat',domain:'一般讨论',title:'AI村长',summary:a.text,facts:[],rows:[],columns:[],recordRows:[],filters:[],evidence:[],tools:[],no_database_query:true},narrative:a.text,generated_at:new Date().toISOString()})}catch{}}
let s:any=null,k:any=null,steps:any[]=[];const ws=p.tools.some((x:any)=>x.tool==='structured_query'),wk=p.tools.some((x:any)=>x.tool==='knowledge_search');if(ws){const a=await structured(req,b).catch(()=>({ok:false}));steps.push({tool:'structured_query',params:{delegated_to:'queryspec-v052',answered:answered(a),trace:a?.plan||null}});if(answered(a))s=a}if(wk||(ws&&!s)){k=await searchKnowledge(db,q,{limit:12,asset_id:ref?.asset_type==='document'?txt(ref.asset_id):null}).catch(()=>null);steps.push({tool:'knowledge_search',params:k?{expanded_terms:k.expansion?.terms||[],embedding_used:k.embedding_used,embedding_model:k.embedding_model,rerank_used:k.rerank_used,candidate_chunks:k.candidate_chunks,matched_chunks:k.matched_chunks,matched_assets:k.matched_assets,indexed_assets:(k.indexed_assets||[]).map((x:any)=>({asset_id:x.asset_id,ok:x.ok,chunks:x.chunks}))}:{failed:true}})}
if(!s&&!k&&p.tools.some((x:any)=>x.tool==='general_response'))try{const a=await general(q);return J({ok:true,model:{mode:'agent-v053-general',name:a.model},plan:{intent:'agent',goal:p.goal,steps:[...steps,{tool:'general_response'}]},result:{kind:'chat',domain:'一般讨论',title:'AI村长',summary:a.text,facts:[],rows:[],columns:[],recordRows:[],filters:[],evidence:[],tools:[],no_database_query:true},narrative:a.text,generated_at:new Date().toISOString()})}catch{}
const f=await fuse(q,s,k),ev=new Set<string>();for(const x of s?.result?.evidence||[])ev.add(String(x));for(const x of k?.sources||[])ev.add(String(x.title));const src=(k?.sources||[]).map((x:any,i:number)=>({source_id:`S${i+1}`,asset_id:x.asset_id,title:x.title,category:x.category,version_label:x.version_label,source_file_name:x.source_file_name,score:+x.best_score||0,excerpts:x.chunks.map((c:any)=>({chunk_id:c.chunk_id,chunk_index:c.chunk_index,text:txt(c.text).slice(0,600),score:+c.score||0}))})),gap=!s&&!k?.sources?.length,msg=gap?`当前已发布资料中还没有找到足够信息回答“${q}”。如果这是村里的真实业务信息，可以让管理员补充相关资料后再问。`:f.text;const result={kind:gap?'data_gap':'agent_answer',domain:'综合知识',title:gap?'暂时没有找到相关资料':'AI村长',summary:msg,document_sections:f.sections||[],conflicts:f.conflicts||[],claims:f.claims||[],facts:[...(s?.result?.facts||[]),...(k?[{label:'命中资料',value:`${k.matched_assets} 份`},{label:'命中片段',value:`${k.matched_chunks} 个`}]:[])],rows:s?.result?.rows||[],columns:s?.result?.columns||[],recordRows:s?.result?.recordRows||[],filters:s?.result?.filters||[],evidence:[...ev],knowledge_sources:src,tools:steps.map(x=>({name:x.tool,desc:x.tool==='knowledge_search'?'V0.5.3 全局知识检索':'V0.5.2 受控结构化查询'})),gap};const fp={intent:'agent',goal:p.goal,planner:{model:p.model,tools:p.tools,answer_scope:p.answer_scope},domains:[...ev],steps,detail:!!result.rows.length||!!src.length,note:'Agent Planner → 能力选择 → 受控执行 → 多源融合'};try{await db.pool.query(`INSERT INTO audit_logs(actor,original_query,model_mode,model_name,plan,result_summary) VALUES('demo-user',$1,'agent-v053',$2,$3::jsonb,$4)`,[q,f.model||p.model,JSON.stringify(fp),msg])}catch{}return J({ok:true,model:{mode:'agent-v053',name:f.model||p.model,gateway:(f.model||p.model)!=='none'},plan:fp,result,narrative:msg,generated_at:new Date().toISOString()})}
export default async(req:Request,_:Context)=>{try{return await handler(req)}catch(e:any){console.error('agent v053 error',e);return J({ok:false,error:'agent_v053_failed',message:e?.message||'AI村长暂时无法处理这个问题。'},{status:500})}};
export const config:Config={path:'/api/agent-v053'};
